### PR TITLE
Response templating configuration

### PR DESCRIPTION
**Pull request by miumum**
I need to configure the templating on client http://wiremock.org/docs/response-templating/

### CODE REVIEW

**Comment by miumum** [comment]
Can I please ask you to merge this?

**Comment by timnederhoff** [comment]
sorry for the late response. I created a new version: https://www.npmjs.com/package/wiremock-easy-client/v/1.4.0

**Comment by miumum** [comment]
Thx for code review. Ad release. But the release seems to be "corrupted" somehow. See https://registry.npmjs.org/wiremock-easy-client/-/wiremock-easy-client-1.4.0.tgz the code is missing there. :( Can you please have a look.

**Comment by timnederhoff** [comment]
Hi @miumum I'm sorry forgot to build the code first 😆 now I created version 1.4.1, https://www.npmjs.com/package/wiremock-easy-client/v/1.4.1

**Comment by miumum** [comment]
Super @timnederhoff thx for quick fix. I can remove the `patch-package` from my project now.

**Pull request merged**
